# Generated by Django 2.0.2 on 2018-04-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('Nombre',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Descripcion', models.CharField(default='none', max_length=40)),
                ('Precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('En_Existencia', models.IntegerField(default=0)),
                ('Codigo', models.CharField(max_length=128)),
                ('Categorias', models.ManyToManyField(to='catalog.Categoria')),
            ],
            options={
                'ordering': ('Nombre',),
            },
        ),
    ]
