# Generated by Django 2.0.2 on 2018-02-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Admin',
        ),
        migrations.AlterUniqueTogether(
            name='products_categories',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='products_categories',
            name='IDCategory',
        ),
        migrations.RemoveField(
            model_name='products_categories',
            name='IDProduct',
        ),
        migrations.AlterUniqueTogether(
            name='sales_products',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sales_products',
            name='IDProduct',
        ),
        migrations.RemoveField(
            model_name='sales_products',
            name='IDSale',
        ),
        migrations.DeleteModel(
            name='Administrators',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Products_Categories',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Sales_Products',
        ),
    ]
