# Generated by Django 2.0.2 on 2018-02-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180226_0222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
