# Generated by Django 2.0.2 on 2018-03-13 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('Nombre',),
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Descripcion', models.CharField(default='none', max_length=40)),
                ('Precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Cantidad', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('Nombre',),
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Folio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Producto')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='folio',
            name='Productos',
            field=models.ManyToManyField(through='administracion.Venta', to='administracion.Producto'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='Productos',
            field=models.ManyToManyField(to='administracion.Producto'),
        ),
    ]
