# Generated by Django 2.0.2 on 2018-03-11 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password_hash', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=40)),
                ('IDAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Administrador')),
            ],
        ),
    ]
