# Generated by Django 2.0.2 on 2018-03-13 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=40)),
                ('Description', models.CharField(default='none', max_length=40)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Categories')),
                ('IDProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalPayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SaleDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('IDProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Products')),
                ('IDSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Sales')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='IDAdmin',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.AlterUniqueTogether(
            name='sales_products',
            unique_together={('IDSale', 'IDProduct')},
        ),
        migrations.AlterUniqueTogether(
            name='products_categories',
            unique_together={('IDProduct', 'IDCategory')},
        ),
    ]
