# Generated by Django 2.0.2 on 2018-03-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Cantidad',
            new_name='En_Existencia',
        ),
    ]
