# Generated by Django 2.0.2 on 2018-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'proxy': True,
                'indexes': [],
            },
            bases=('administracion.folio',),
        ),
    ]
