# Generated by Django 2.0.2 on 2018-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='TicketFolio',
            field=models.CharField(default='http://127.0.0.1:8000/ticket/<built-in function id>/', max_length=70),
        ),
    ]
