# Generated by Django 2.0.2 on 2018-05-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_folio_ticketfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folio',
            name='TicketFolio',
        ),
    ]
