# Generated by Django 2.0.2 on 2018-03-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20180313_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='Productos',
        ),
        migrations.AddField(
            model_name='producto',
            name='Categorias',
            field=models.ManyToManyField(to='administracion.Categoria'),
        ),
    ]
