# Generated by Django 2.0.2 on 2018-05-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20180512_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReporteDeVentas',
            new_name='Reporte',
        ),
    ]
