# Generated by Django 2.0.2 on 2018-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20180313_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.CharField(default='', max_length=300),
        ),
    ]
